### ISSUE TITLE
Use Ansible Vault to encrypt secrets

### ISSUE THREAD

**Issue by chThie** [healthIMIS/internal-tools#27]
https://docs.ansible.com/ansible/latest/user_guide/vault.html
https://www.redhat.com/sysadmin/ansible-playbooks-secrets

Something like:
### Task config
```
  tasks:
    - name: Ensure API key is present in config file
      ansible.builtin.lineinfile:
        path: /etc/app/configuration.ini
        line: "API_KEY={{ api_key }}"
      no_log: True
```
### Encrypt yaml config file containing secrets
```
$ cat secrets_file.enc
> api_key: SuperSecretPassword

$ ansible-vault encrypt secrets_file.enc
```

### Run playbook with passphrase or password file (!permissions!)
```$ ansible-playbook -i inventory.ini -e @secrets_file.enc --ask-vault-pass main.yml```  
or 
```
$ cat password_file 
> password
$ ansible-playbook -i inventory.ini -e @secrets_file.enc --vault-password-file password_file main.yml```
